version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "consumer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vedfvs972p0f"
s3_prefix = "consumer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=057657186817.dkr.ecr.us-east-1.amazonaws.com/consumer"]
